### ISSUE TITLE
After using this mod, I get a lot of "Not Enough Customers" warnings in the city every morning. Is this normal?

### ISSUE THREAD

**Issue by esbylan** [ruzbeh0/Time2Work#2]
By the way, I am using the default settings of the mod.

**Comment by ruzbeh0** [comment]
I'm aware of this issue. But I'm waiting for CO to release the new economy patch to look into it. I don't want to work on this now since they will probably do a lot of changes in the economy

**Comment by esbylan** [comment]
I got it.Thank you :）
